<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta name="ero_verify" content="ec74b5727402749048f82a51a38cd8ca" />
        <meta charset="utf-8">
        <?php echo $this->headTitle('http://www.tocadasnovinhas.com.br/'. $this->translate('Toca das Novinhas'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/shop-homepage.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <!-- BEGIN EroAdvertising ADSPACE CODE -->
      <script type="text/javascript" language="javascript" charset="utf-8" src="//adspaces.ero-advertising.com/adspace/2120107.js"></script>
      <!-- END EroAdvertising ADSPACE CODE -->

        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Toca das Novinhas</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">Fotos</a>
                    </li>
                    <li>
                        <a href="#">Videos</a>
                    </li>
                    <li>
                        <a href="#">WhatsApp</a>
                    </li>
                    <li>
                        <a href="#">Gringas</a>
                    </li>
                    <li>
                        <a href="#">Caiu na Net</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-md-3">
                <p class="lead">Categorias</p>
                <div class="list-group">
                    <a href="http://www.tocadasnovinhas.com.br/application/index/category/loiras" class="list-group-item">Loiras</a>
                    <a href="http://www.tocadasnovinhas.com.br/application/index/category/gay" class="list-group-item">Gay</a>
                    <a href="http://www.tocadasnovinhas.com.br/application/index/category/novinhas" class="list-group-item">Novinhas</a>

                    <!-- <a href="application/index/category/boquetes" class="list-group-item">Boquetes</a>
                    <a href="application/index/category/celebridades" class="list-group-item">Celebridades</a>
                    <a href="application/index/category/creampie" class="list-group-item">Creampie</a>
                    <a href="application/index/category/camera-escondida" class="list-group-item">Câmeras escondidas</a>
                    <a href="application/index/category/desenhos" class="list-group-item">Desenhos</a>
                    <a href="application/index/category/gay" class="list-group-item">Gay Porn</a>
                    <a href="application/index/category/gangbang" class="list-group-item">GangBang</a>
                    <a href="application/index/category/latinos" class="list-group-item">Latinos</a>
                    <a href="application/index/category/lesbicas" class="list-group-item">Lésbicas</a>
                    <a href="application/index/category/punhetas" class="list-group-item">Punhetas</a> -->
                </div>
            </div>

            <div class="col-md-9">
              <?=$this->content;?>
            </div>

        </div>

    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Toca das Novinhas 2016</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

        <?php echo $this->inlineScript() ?>
        <!-- BEGIN EroAdvertising ADSPACE CODE -->
        <script type="text/javascript" language="javascript" charset="utf-8" src="//adspaces.ero-advertising.com/adspace/2120140.js"></script>
        <!-- END EroAdvertising ADSPACE CODE -->
    </body>
</html>
