<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta name="ero_verify" content="ec74b5727402749048f82a51a38cd8ca" />
        <meta charset="utf-8">
        <?php echo $this->headTitle(''. $this->translate('Toca das Novinhas'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        // ->prependStylesheet($this->basePath() . '/css/shop-homepage.css')
                        ->prependStylesheet($this->basePath() . '/css/main.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
      <div class="outer-wrap">
        <header class="masthead">

        <div class="centered">
          <div>
            	<img src="http://www.tocadasnovinhas.com.br/img/banner.png"></img>
          </div><!-- .site-title -->
        </div><!-- .centered -->

          <div class="main-menu">
            <div class="nav-mixed menu">
              <nav id="multi-level-nav" class="multi-level-nav" role="navigation">
                <ul>
                  <li><a href="http://www.tocadasnovinhas.com.br/blog/fotos">Playboy</a></li>
                  <li><a href="#">Revista Sexy (Em Breve)</a></li>
                </ul>
              </nav><!-- #multi-level-nav .multi-level-nav -->

              <nav id="social-menu" class="social-menu" role="navigation">
                <!-- <ul>
                  <li><a href="https://twitter.com/bugsyAlexander"><span class="screen-reader-text">Twitter</span></a></li>
                  <li><a href="https://github.com/bugsyAlexander"><span class="screen-reader-text">Github</span></a></li>
                  <li><a href="https://www.linkedin.com/pub/mynor-alexander/5b/943/877"><span class="screen-reader-text">LinkedIn</span></a></li>
                  <li><a href="http://dribbble.com"><span class="screen-reader-text">Dribbble</span></a></li>
                  <li><a href="http://instagram.com"><span class="screen-reader-text">Instagram</span></a></li>
                </ul> -->
              </nav> <!-- .social-menu -->
            </div><!-- .mixed-menu -->
            </div><!-- main-menu -->
          </header><!-- .masthead -->

          <div class="content">
            <?=$this->content;?>
            <div class="sidebar">
              <div class="squish-container">
                <h3>Categorias</h3>
                <nav class="example-menu">
                  <ul>
                    <!-- <li><a href="http://codepen.io/bugsyAlexander/pen/xGBaaG" target="_blank">Mixed Menu</a></li>
                    <li><a href="http://codepen.io/bugsyAlexander/pen/gpyYOo" target="_blank">Card Layout</a></li>
                    <li><a href="http://codepen.io/bugsyAlexander/pen/OVGLmo" target="_blank">Holy Grail</a></li>
                    <li><a href="http://codepen.io/bugsyAlexander/pen/xGNZao" target="_blank">Site Demo</a></li> -->
                    <li><a href="http://www.tocadasnovinhas.com.br/blog/categoria/amador" >Amador</a></li>
                    <li><a href="http://www.tocadasnovinhas.com.br/blog/categoria/anal" >Anal</a></li>
                    <li><a href="http://www.tocadasnovinhas.com.br/blog/categoria/boquete" >Boquetes</a></li>
                    <li><a href="http://www.tocadasnovinhas.com.br/blog/categoria/funk" >Funk</a></li>
                    <li><a href="http://www.tocadasnovinhas.com.br/blog/categoria/namorada" >Namoradas</a></li>
                    <li><a href="http://www.tocadasnovinhas.com.br/blog/categoria/novinhas" >Novinhas</a></li>
                    <li><a href="http://www.tocadasnovinhas.com.br/blog/categoria/siririca" >Siriricas</a></li>
                    <li><a href="http://www.tocadasnovinhas.com.br/blog/categoria/loiras" >Loiras</a></li>
                  </ul>
                </nav><!-- .example-menu -->
              </div>
            </div><!-- .sidebar -->
          </div><!-- .content -->

        <footer class="footer-area">
          <p>&copy; 2015 Some copyright message - All rights reserved</p>
        </footer>
      </div><!-- .outer-wrap -->

        <?php echo $this->inlineScript() ?>
        <!-- BEGIN EroAdvertising ADSPACE CODE -->
        <script type="text/javascript" language="javascript" charset="utf-8" src="//adspaces.ero-advertising.com/adspace/2120140.js"></script>
        <!-- END EroAdvertising ADSPACE CODE -->
    </body>
</html>
