<main class="main-area">
<div class="centered">
      <section class="cards">
<?php foreach ($data as $d) : ?>
      <article class="card">
        <a href="#">
          <figure class="thumbnail">
            <img src="<?=$d->img?>" alt="meow">
          </figure>
          <div class="card-content" style="padding:0.5em !important">
            <span style="color:rgb(9, 158, 30);font-size:13px"><?=strtoupper($d->category)?></span>
            <br>
            <span style="color:gray; text-decoration: underline;
    font-size: 0.9em;"><?=$d->description?></span>
          </div><!-- .card-content -->
        </a>
      </article><!-- .card -->

  <?php endforeach; ?>
</section><!-- .cards -->
</div><!-- .centered -->

</main><!-- main-area -->
