<main class="main-area">
<div class="centered">
      <section class="cards">
<?php foreach ($data as $d) : ?>
      <article class="card">
        <a href="#">
          <figure class="thumbnail">
            <img src="<?=$d->img?>" alt="meow">
          </figure>
          <div class="card-content">
            <h5><?=$d->name?></h5>
          </div><!-- .card-content -->
        </a>
      </article><!-- .card -->

  <?php endforeach; ?>
</section><!-- .cards -->
</div><!-- .centered -->

</main><!-- main-area -->
