<!-- Portfolio Item Heading -->
 <!-- /.row -->
 <?php foreach ($data as $d) : ?>
   <div class="well">
       <small><?=$d->name?></small>
        </hr>
         <?=$d->embed?>
   </div>

 <?php endforeach; ?>

 <!-- Related Projects Row -->
 <div class="row">

     <div class="col-lg-12">
         <h3 class="page-header">Videos relacionados</h3>
     </div>
     <?php foreach ($relacionado as $r) : ?>
     <div class="col-sm-3 col-xs-6">
         <a href="http://www.tocadasnovinhas.com.br/application/index/detail/<?=$r->name?>">
             <img class="img-responsive portfolio-item" src="<?=$r->img?>" alt="">
         </a>
        <?=$r->name?>
     </div>
      <?php endforeach; ?>
 </div>
