<main class="main-area">
<div class="centered">
      <section class="cards">
<?php foreach ($this->paginator as $d) : ?>
      <article class="card">
        <a href="#">
          <figure class="thumbnail">
            <img src="<?=$d->img?>" alt="meow">
          </figure>
          <div class="card-content">
            <h5><?=$d->name?></h5>
          </div><!-- .card-content -->
        </a>
      </article><!-- .card -->

  <?php endforeach; ?>
</section><!-- .cards -->
</div><!-- .centered -->
</main><!-- main-area -->
  <hr>
  <?php
  // add at the end of the file after the table
  echo $this->paginationControl(
      // the paginator object
      $this->paginator,
      // the scrolling style
      'sliding',
      // the partial to use to render the control
      'partial/paginator.phtml',
      // the route to link to when a user clicks a control link
      array(
          'route' => 'home'
      )
  );
  ?>
