<main class="main-area">
<div class="centered">
      <section class="cards">
<?php foreach ($this->paginator as $d) : ?>
      <article class="card">
        <a href="http://www.tocadasnovinhas.com.br/application/index/detail/<?=$d->name?>">
          <figure class="thumbnail">
            <img src="<?=$d->img?>" alt="meow"><div style="width: 40px;height: 25px;background:black;opacity: 0.7;position: absolute;color: white;font-weight: bolder;margin-top:-25px">(3:30)</div></img>
          </figure>
          <div class="card-content">
            <span style="color:gray"><?=$d->name?></span>
          </div><!-- .card-content -->
        </a>
      </article><!-- .card -->

  <?php endforeach; ?>
</section><!-- .cards -->
</div><!-- .centered -->
<center>
<?php
// add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style
    'sliding',
    // the partial to use to render the control
    'partial/paginator.phtml',
    // the route to link to when a user clicks a control link
    array(
        'route' => 'home'
    )
);
?>
</center>
</main><!-- main-area -->
