<main class="main-area">
<div class="centered">
      <section class="cards">
<?php foreach ($this->paginator as $d) : ?>
      <article class="card">
        <a href="http://www.tocadasnovinhas.com.br/blog/videos/<?=$d->name?>">
          <figure class="thumbnail">
            <img src="<?=$d->img?>" alt="meow"><div style="width: 64px;height: 20px;background:black;opacity: 0.7;position: absolute;color: white;font-weight: bolder;margin-top:-20px;font-size:10px;font-family: inherit;padding:3px"><?=$d->tempo?></div></img>
          </figure>
          <div class="card-content" style="padding:0.5em !important">
            <span style="color:rgb(9, 158, 30);font-size:13px"><?=strtoupper($d->category)?></span>
            
            <span style="color:gray; text-decoration: underline;
    font-size: 0.9em;"><?=$d->description?></span>
          </div><!-- .card-content -->
        </a>
      </article><!-- .card -->

  <?php endforeach; ?>
</section><!-- .cards -->
</div><!-- .centered -->
<center>
<?php
// add at the end of the file after the table
echo $this->paginationControl(
    // the paginator object
    $this->paginator,
    // the scrolling style
    'sliding',
    // the partial to use to render the control
    'partial/paginator.phtml',
    // the route to link to when a user clicks a control link
    array(
        'route' => 'home'
    )
);
?>
</center>
</main><!-- main-area -->
