<main class="main-area">
<div class="centered">
 <?php foreach ($data as $d) : ?>
  <?=$d->description?>
  <hr>
  <?=$d->embed?>
<?php endforeach; ?>

</div>
<br>
Tags:
<a href="/category/amadoras/" rel="category tag">Amadoras</a>
<a href="/category/amadoras/" rel="category tag">Loiras</a>
<a href="/category/amadoras/" rel="category tag">Rabuda</a>
<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Videos relacionados</h3>
    </div>
    <?php foreach ($relacionado as $r) : ?>
    <div class="col-sm-3 col-xs-6">
        <a href="http://www.tocadasnovinhas.com.br/blog/videos/<?=$r->name?>">
            <img class="img-responsive portfolio-item" src="<?=$r->img?>" alt="">
        </a>
       <?=$r->description?>
    </div>
     <?php endforeach; ?>
</div>
</main>
